sonar.organization=maykb
sonar.projectKey=MayKB_devops-hands-on-project-hivebox

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.