# https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.organization=maykb
sonar.projectKey=MayKB_devops-hands-on-project-hivebox

sonar.sources=.
sonar.exclusions = tests/
sonar.tests=tests/

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12, 3.13, 3.14