name: Release

on:
  pull_request:
    types: [closed]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: read
    if: github.event.pull_request.merged
    steps:
      - name: Tag
        uses: K-Phoen/semver-release-action@1a1fc63a95a12b4bb535b53ab0d861bce53ce89d # v1.3.2
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}