name: SonarQube Workflow

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

permissions:
  actions: read
  artifact-metadata: read
  attestations: read
  checks: read
  code-quality: read
  contents: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  security-events: read
  statuses: read

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
    - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
          python -m pip install --require-hashes --upgrade pip
          pip install --only-binary :all: --require-hashes -r app-requirements.txt
          pip install --only-binary :all: --require-hashes -r test-and-scan-requirements.txt

    - name: Run tests with coverage
      run: pytest --cov=. --cov-report=xml

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
