# Acknowledgements:
## https://anand-rohan.medium.com/using-pylint-for-python-code-analysis-in-github-actions-878b61639623
## https://github.com/actions/starter-workflows/blob/main/ci/pylint.yml
## https://docs.docker.com/build/ci/github-actions/local-registry/

name: Lint Build and Test

on: [push]

permissions: read-all

jobs:
  pylint:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  lint-dockerfile:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile
  
  docker:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver-opts: network=host
      
      - name: Build and push to local registry
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: localhost:5000/name/app:latest
      
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest

  test-version:
    runs-on: ubuntu-latest
    permissions:
        contents: read
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests/